version: '3'
services:
        front:
                build: ./web
                container_name: "zukan-web"
                expose:
                        - "80"
                network_mode: host
                depends_on:
                        - back
        back:
                container_name: "zukan-api"
                build: ./backend
                ports:
                        - 3001:3001