version: 2.1

executors:
  default-executor:
    machine: true

jobs:
  build-job:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Build Image Web
          command: >
            docker build -t ${WEB_IMAGE_TAG} ./web
      - run:
          name: Build Image Api
          command: >
            docker build -t ${API_IMAGE_TAG} ./backend
  deploy-job:
    executor: default-executor
    steps:
      - run: echo "Setup AWS CLI"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master