version: 2.1

executors:
  default-executor:
    machine: true

jobs:
  build-job:
    executor: default-executor
    steps:
      - checkout
      - run:
        name: Build Image Web
        command: >
          echo "Build Image Web"
      - run:
        name: Build Image Api
        command: >
          echo "Build Image Api"
  deploy-job:
    executor: default-executor
    steps:
      - run:
        name: Setup AWS CLI
        command: >
          echo "Setup AWS CLI"
      - run:
        name: Auth Docker Client
        commnad: >
          echo "Auth Docker Client"
      - run:
        name: Push Image Web
        command: >
          echo "Push Image Web"
      - run:
        name: Push Image Api
        command: >
          echo "Push Image Api"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master